### ISSUE TITLE
all test failing on mingw

### ISSUE THREAD

**Issue by rkanavath** [sertit/SertitObject#3]
Since there is no update on msvc issues. I moved sertit to mingw. But the tests are still failing.

http://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=214090

I am wondering why the are not appearing on linux. Is there something specific to unix in the code ?

```
 apSertitObjectRadiometricStatistics (Failed) 
2016 Jan 11 03:46:06  :  Application.logger  (FATAL) The following error occurred during application execution : /data/dashboard/nightly/otb-Release/src/Modules/Adapters/GdalAdapters/src/otbOGRDataSourceWrapper.cxx:483:
itk::ERROR: DataSource(0x7a8c410): Cannot fetch 0th layer in the GDALDataset <> as it contains only 0layers.

```

The other test seems like another memory alloc error

```
Test: apSertitObjectAggregate (Failed) 
2016 Jan 11 03:46:02  :  Application.logger  (INFO) Number of objects: 301
2016 Jan 11 03:46:02  :  Application.logger  (INFO) Number of classes: 458470
2016 Jan 11 03:46:02  :  Application.logger  (INFO) Minimum: 17521
2016 Jan 11 03:46:04  :  Application.logger  (FATAL) The following error occurred during application execution : /data/tools/mxe/tmp-itk-i686-w64-mingw32.shared/InsightToolkit-4.8.2/Modules/Core/Common/src/itkMultiThreader.cxx:416:
itk::ERROR: MultiThreader(0x7f46fa8): Exception occurred during SingleMethodExecute
std::bad_alloc
-> Test EXIT FAILURE (1).
otbTestMain 'Execute': ITK Exception thrown:
/data/dashboard/nightly/otb-Release/src/Modules/IO/TestKernel/include/otbTestMain.h:300:
itk::ERROR: Function returns EXIT_FAILURE (not from regression, failure inside the test)
```

**Comment by ghost** [comment]
Dear Rashad,

Thanks for updates. There is not specific code for Unix, so I don't understand the fail.

I haven't had so much time to deal with that code in the previous months, but I definitely need to compile OTB on Windows to check what's wrong. I planned to do that next month.

Thanks again, best wishes for this new year !

**Comment by rkanavath** [comment]
I understand the lack of testing on windows. This is exactly why I moved to mingw. Now you can setup a mxe (http://mxe.cc) environment to produce the  windows binaries on a linux machine!.

Or you can see the how to for settting up a windows environment on a windows machine( wiki page on otb site) as you prefer.

happy new year to you and all the best with debugging..

**Comment by ghost** [comment]
Hi Rashad,
After looking at it, the problem seems to come from the file QB_Toulouse_Ortho_XS.tif which is used in the first test, instead of a pixel-oriented classification.
Is there any classification derived from QB_Toulouse_Ortho_XS.tif in the OTB-Data directory that I can use in my test ?
If no, how I can generate it in the CMakeLists.txt without using otb_test_application() ?

**Comment by rkanavath** [comment]
could you ask this on otb-developers list?
